# as of 04-17-15 can be just

addons:
  apt:
    packages:
      - libgsl2
      - gsl-bin
      - libgsl-dev
      - libmagick++-dev

language: r
sudo: required

##because of phangorn
#bioc_packages:
#   - Biostrings

# Be strict when checking our package
warnings_are_errors: true

# r_check_args: --as-cran --run-donttest 

# for code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

###########
#OLD: brought back due to r-travis not failing bad builds


# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
 
# language: c
# sudo: required
 
# env:
# - WARNINGS_ARE_ERRORS=1
 
# before_install:
#   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#   - ./travis-tool.sh bootstrap
 
# install:
#   - ./travis-tool.sh install_deps
 
# script: ./travis-tool.sh run_tests
 
# on_failure:
#   - ./travis-tool.sh dump_logs
 
# notifications:
#   email:
#     on_success: change
#     on_failure: change