footeValues<-function(p,q,r,PA_n=0,PB_1=0,p_cont=TRUE,q_cont=TRUE,Nb=1){
	#set '03 Table Values
	#following relies on sep p, q, r of all intervals
	n<-length(p)
	#Nbt
	if(q_cont){
		Nbt<-Nb*exp(-q)
	}else{
		Nbt<-Nb*(1-q)
		}
	#NbL
	if(q_cont){
		NbL<-Nb*(1-exp(-q))
	}else{
		NbL<-Nb*q
		}
	#NFt
	if(p_cont){
		if(q_cont){
			NFt<-Nb*exp(p-q)*(1-exp(-p))
		}else{
			NFt<-Nb*exp(p)*(1-q)*(1-exp(-p))
			}
	}else{
		if(q_cont){
			NFt<-Nb*p*exp(-q)
		}else{
			NFt<-Nb*p*(1-q)
			}
		}
	#NFL
	NFL<-numeric()
	if(p_cont){
		if(q_cont){
			for(i in 1:n){
				if(p[i]==q[i]){
					NFL[i]<-Nb*(exp(-q[i])+p[i]-1)
				}else{
					NFL[i]<-Nb*(((q[i]*exp(p[i]-q[i]))+((p[i]-q[i])*exp(-q[i]))-p[i])/(p[i]-q[i]))
					}
				}
		}else{
			NFL<-Nb*q*(exp(p)-1)
			}
	}else{
		if(q_cont){
			NFL<-Nb*p*(1-exp(-q))
		}else{
			NFL<-Nb*p*q
			}
		}
	#PD_bt
	PD_bt<-1-exp(-r)
	#PD_bL
	if(q_cont){
		PD_bL<-(((r+q*exp(-(q+r)))/(q+r))-exp(-q))/(1-exp(-q))
	}else{
		PD_bL<-1-exp(-r)
			}
	#PD_Ft
	if(p_cont){
		PD_Ft<-(((r+p*exp(-(p+r)))/(p+r))-exp(-p))/(1-exp(-p))
	}else{
		PD_Ft<-1-exp(-r)
		}
	#PD_FL
	if(p_cont){
		if(q_cont){
			PD_FL<-numeric()
			for(i in 1:n){
				if(p[i]==q[i]){
					PD_FL[i]<-(Nb*p[i]/NFL[i])*((r[i]/(p[i]+r[i]))-((1-exp(-p[i]))/p[i])
						+(p[i]*(1-exp(-(p[i]+r[i])))/((p[i]+r[i])^2)))
				}else{
					PD_FL[i]<-(Nb/NFL[i])*(((p[i]*r[i]*(exp(p[i]-q[i])-1))/((q[i]+r[i])*(p[i]-q[i])))
						+((p[i]*q[i]*exp(-(q[i]+r[i]))*(exp(p[i]+r[i])-1))/((p[i]+r[i])*(q[i]+r[i])))
						-(exp(-q[i])*(exp(p[i])-1)))
					}
				}
		}else{
			PD_FL<-(-((p*(-exp(-r))-(exp(p)*r)+p+r)/((exp(p)-1)*(p+r))))
			}
	}else{
		if(q_cont){
			PD_FL<-(-((q*(-exp(-r))-(exp(q)*r)+q+r)/((exp(q)-1)*(q+r))))
		}else{
			PD_FL<-1-exp(-r)
			}
		}
	#PA for a given i
	PA<-numeric()
	PA[n]<-PA_n
	for(i in 1:(n-1)){
		if(q_cont){
			PA_i<-0
			for(k in (i+1):n){
				if((i+1)<=(k-1)){m<-(i+1):(k-1)}else{m<-NA}
				PA_i<-PA_i+ifelse(is.na(m[1]),1,exp(-sum(q[m])))*(1-exp(-q[k]))*(1-(
					ifelse(is.na(m[1]),1,exp(-sum(r[m])))*(1-PD_bL[k])))
				}
			PA[i]<-PA_i+(exp(-sum(q[(i+1):n])))*(1-exp(-sum(r[(i+1):n]))*(1-PA[n]))
		}else{
			PA_i<-0
			for(k in (i+1):n){
				if((i+1)<=(k-1)){m<-(i+1):(k-1)}else{m<-NA}
				PA_i<-PA_i+ifelse(is.na(m[1]),1,prod(1-q[m]))*q[k]*(1-(
					ifelse(is.na(m[1]),1,exp(-sum(r[m])))*(1-PD_bL[k])))
				}
			PA[i]<-PA_i+(prod(1-q[(i+1):n])*(1-exp(-sum(r[(i+1):n]))*(1-PA[n])))
			}
		}
	#PB
	PB<-numeric()
	PB[1]<-PB_1
	for(i in 2:n){
		if(p_cont){
			PB_i<-0
			for(k in 1:(i-1)){
				if((k+1)<=(i-1)){m<-(k+1):(i-1)}else{m<-NA}
				PB_i<-PB_i+((ifelse(is.na(m[1]),1,exp(-sum(p[m])))*(1-exp(-p[k])))*(1-
					ifelse(is.na(m[1]),1,exp(-sum(r[m])))*(1-PD_Ft[k])))
				}
			PB[i]<-PB_i+(exp(-sum(p[1:(i-1)])))*(1-exp(-sum(r[1:(i-1)]))*(1-PB[1]))
		}else{
			PB_i<-0
			for(k in 1:(i-1)){
				if((k+1)<=(i-1)){m<-(k+1):(i-1)}else{m<-NA}
				PB_i<-PB_i+((ifelse(is.na(m[1]),1,prod(1/(1+p[m])))*(p[k]/(1+p[k])))*(1-
					ifelse(is.na(m[1]),1,exp(-sum(r[m])))*(1-PD_Ft[k])))
				}
			PB[i]<-PB_i+(prod(1/(1+p[1:(i-1)]))*(1-exp(-sum(r[1:(i-1)]))*(1-PB[1])))
			}
		}
	#Xbt
	Xbt<-Nbt*PB*PA
	#XbL
	XbL<-NbL*PB*PD_bL+Nbt*PB*PD_bt*(1-PA)
	#XFt
	XFt<-NFt*PA*PD_Ft+Nbt*PA*PD_bt*(1-PB)	
	#XFL
	XFL<-(NFL*PD_FL)+(NbL*(1-PB)*PD_bL)+(NFt*(1-PA)*PD_Ft)+(Nbt*(1-PB)*PD_bt*(1-PA))
	res<-data.frame(cbind(Nb=rep(Nb,n),Nbt,NbL,NFt,NFL,PD_bt,PD_bL,PD_Ft,PD_FL,PA,PB,Xbt,XbL,XFt,XFL))
	return(res)
	}